added header
Marina2771/Diploma pull request #2
Opened 2021-11-25 18:57 UTC by Marina2771

Добавила хэдер, пока без адаптива)

2021-11-26 10:52 UTC, aleksey-drozdov requested changes

2021-11-26 10:52 UTC, aleksey-drozdov commented on package.json
> +  "author": "Aleksey Drozdov <leshadrozdov@gmail.com>",
тут стоит заменить имя и почту на свои

2021-11-26 10:52 UTC, aleksey-drozdov commented on src/components/header.pug
> +            img(src="../assets/images/Header_logo.png", alt="")
в данном случае путь к файлу должен быть или /assets/...  или  assets/...

2021-11-26 10:52 UTC, aleksey-drozdov commented on src/assets/styles/styles.scss
> +@import "sections/footer";
стили для футера должны идти в конце

2021-11-26 10:52 UTC, aleksey-drozdov commented on src/assets/styles/util/_mixins.scss
> +@mixin main_button {
подключить перед миксином файл с цветами

2021-11-26 10:52 UTC, aleksey-drozdov commented on src/assets/styles/sections/_header.scss
> +    padding: 30px 0;
тут паддинги лучше написать именно через padding-top и для ниэнего так же. потому что у нас есть паддинги слева и справа у класса container  и такой записью как сейчас мы перебиваем их в ноль.

2021-11-27 11:50 UTC, Marina2771 commented on package.json
> +  "author": "Aleksey Drozdov <leshadrozdov@gmail.com>",
исправила

2021-11-27 11:50 UTC, Marina2771 commented on src/components/header.pug
> +            img(src="../assets/images/Header_logo.png", alt="")
исправила

2021-11-27 11:52 UTC, Marina2771 commented on src/assets/styles/styles.scss
> +@import "sections/footer";
исправила

2021-11-27 11:54 UTC, Marina2771 commented on src/assets/styles/util/_mixins.scss
> +@mixin main_button {
исправила

2021-11-27 11:55 UTC, Marina2771 commented on src/assets/styles/sections/_header.scss
> +    padding: 30px 0;
исправила

2021-11-28 13:55 UTC, aleksey-drozdov approved these changes

2021-11-28 13:57 UTC, merged