Feat/section how it works
Marina2771/Diploma pull request #6
Opened 2021-11-30 13:27 UTC by Marina2771

создала новый ПР, т.к. в первый раз неуказала ветку dev

2021-12-01 13:35 UTC, aleksey-drozdov requested changes

2021-12-01 13:35 UTC, aleksey-drozdov commented on src/components/section_how_it_works.pug
> +                img.dog_circle (src="assets/images/dog_circle.png", alt="")
убрать проьел перед открывающейся скобкой. из-за этого сборка не запускается

2021-12-01 13:35 UTC, aleksey-drozdov commented on src/components/section_how_it_works.pug
> +            .content_item
не лучше использование заголовков. вместо h2 лучше писать h5 какой-нибудь. а h4 и h3 в других каротчках заменить на p. плюс проверить почему тект отличается по стилям от макета

2021-12-01 13:35 UTC, aleksey-drozdov commented on src/assets/styles/sections/_section_how_it_works.scss
> +
вместо того, что бы раздвигать карточки падингами, лучше на родителя флексы навесить

2021-12-01 13:35 UTC, aleksey-drozdov commented on src/assets/styles/sections/_section_how_it_works.scss
> +    padding-bottom: 16px;
из-за пробела перед : код не совсем правильно работает

2021-12-01 16:45 UTC, Marina2771 commented on src/components/section_how_it_works.pug
> +                img.dog_circle (src="assets/images/dog_circle.png", alt="")
готово

2021-12-01 16:57 UTC, Marina2771 commented on src/components/section_how_it_works.pug
> +            .content_item
теги изменила, со шрифтами все по макету, но отображаются в фигме более жирными

2021-12-01 17:14 UTC, Marina2771 commented on src/assets/styles/sections/_section_how_it_works.scss
> +
сделано, jc space-b

2021-12-01 18:16 UTC, Marina2771 commented on src/assets/styles/sections/_section_how_it_works.scss
> +    padding-bottom: 16px;
сделано

2021-12-02 08:34 UTC, aleksey-drozdov commented on src/components/section_how_it_works.pug
> +                    p we reach out to them for you. Whatever is easiest!
почему на одной карточке структура отличается от других?

2021-12-02 13:40 UTC, Marina2771 commented on src/components/section_how_it_works.pug
> +                    p we reach out to them for you. Whatever is easiest!
сделала чтобы перенести текст, т.к. | не отработал перенос

2021-12-04 09:54 UTC, aleksey-drozdov approved these changes

2021-12-04 14:21 UTC, merged